server:
  port: 8081

#  address: 192.168.0.71
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dopaminex.c9ey8eai2kkp.ap-northeast-2.rds.amazonaws.com:3306/dopaminex?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root # RDS 사용자명
    password: 1q2w3e4r! # RDS 비밀번호
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret:
    key: 7J2064W467Kg7J207IWY7Lqg7ZSE7IiY6rCV7IOd67aE65Ok7ZmU7J207YyF7ZWY7IS47JqU7KKL7J2A7ZqM7IKs7JeQ66qo65GQ7Leo7JeF7ISx6rO17ZWY7Iuk6rGw652866+/7Iq164uI64uk65287J2067iM7IS47IWY65Ok7Ja07KO87IWU7ISc6rCQ7IKs7ZWp64uI64uk64+E7JuA7J2065CY7JeI7Jy866m07KKL6rKg7Iq164uI64uk

  websocket:
    endpoint: /ws/chat

jasypt:
  encryptor:
    password: jasyptStringEncryptor  # 암호화 문자열

cloud:
  aws:
    credentials:
      access-key: AKIA6ELKOBDPXDMU3Y7M
      secret-key: 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
    region:
      static: ap-northeast-2  # AWS S3 리전
    stack:
      auto: false

application:
  bucket:
    name: joo-legend  # AWS S3 버킷 이름

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
    file:
      upload-dir: C:/uploads  # 허용된 업로드 경로 설정

resilience4j.circuitbreaker:
  instances:
    myServiceCircuitBreaker:
      slidingWindowSize: 100
      failureRateThreshold: 50
      waitDurationInOpenState: 5000ms
      permittedNumberOfCallsInHalfOpenState: 10
