<<<<<<< HEAD
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dopamine_x?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 11111111

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret:
    key: 7J2064W467Kg7J207IWY7Lqg7ZSE7IiY6rCV7IOd67aE65Ok7ZmU7J207YyF7ZWY7IS47JqU7KKL7J2A7ZqM7IKs7JeQ66qo65GQ7Leo7JeF7ISx6rO17ZWY7Iuk6rGw652866+/7Iq164uI64uk65287J2067iM7IS47IWY65Ok7Ja07KO87IWU7ISc6rCQ7IKs7ZWp64uI64uk64+E7JuA7J2065CY7JeI7Jy866m07KKL6rKg7Iq164uI64uk

jasypt:
  encryptor:
    password: jasyptStringEncryptor  # ???? ??? ?
=======
#spring.application.name=backend-function
#MySQL \uC124\uC815
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backend-function
    username: ${DB_USER}
    password: ${DB_PW}
  sql:
    init:
      mode: never
    # \uC815\uB82C \uBC29\uC2DD
    # always \uD56D\uC0C1 , embedded : \uADF8\uC7A5 DB\uB9CC never : \uBAA8\uB4E0 \uB3D9\uC791 \uC548\uD568
  jpa:
    # spring.sql.init \uCD08\uAE30\uD654 \uD560\uB54C \uB370\uC774\uD130 \uC785\uB825\uC744 \uC704\uD55C \uB9AC \uC791\uC5C5\uC744 \uBC30\uCE58 \uD560\uAC83
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

>>>>>>> 7f697c59ad99e5ec06f65e4489bade8012c73198
